name: Test code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@arunnalla'
      - run: npm ci
      - run: npm test
